[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"] }

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "mining_comparaison"
harness = false

[lib]
name = "lib_block"
path = "src/block_chain/block.rs"
