[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
w3f-bls = "0.1.3"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "mining_comparaison"
harness = false

[lib]
name = "block_chain"
path = "src/block_chain/mod.rs"